### ISSUE TITLE
自定义布局css笔记

### ISSUE THREAD

**Issue by GjXing** [GjXing/vueBlog#16]
### `v-row` `v-col` `v-col-1~24` 布局
```
<div class="v-row">
  <div class="v-col v-col-16">
    <div class="v-grid-content"></div>
  </div>
  <div class="v-col v-col-8">
    <div class="v-grid-content"></div>
  </div>	
</div>
<div class="v-row">
  <div class="v-col v-col-16">
    <div class="v-grid-content"></div>
  </div>
  <div class="v-col v-col-8">
    <div class="v-grid-content"></div>
  </div>	
</div>
<div class="v-row">
  <div class="v-col v-col-24">
    <div class="v-grid-content"></div>
  </div>
</div>
```

### v-title 标题
```
<!-- 标题 -->
<div class="v-title">
  <h1>实时概况</h1>			
</div>
```

### v-text 文本
```
<div class="v-text">
  <p>支付金额（元）</p>
  <h2>18,604</h2>
</div>
```

### v-icon 图标
```
<div class="v-icon v-bg">
  <i class="icon-recon"></i>
</div>
```

### v-row-flex `flex` 布局
```
<div class="v-row-flex"></div>
```

```css
/*
 * mego.css
 * 2017.11.14 gjb
 *
*/
/* 布局 */
.v-h20{ height:.8rem;}
.v-h40{ height: 1.6rem;}
.v-box{
	max-width:1280px;
	margin: 0 auto;
	padding: .8rem;
}
.v-row{
	position: relative;
	margin-left: -.4rem;
    margin-right: -.4rem;
    margin-bottom: .8rem;
    box-sizing: border-box;
    display: block;
}
.v-row:after,
.v-row:before {
    display: table;
    content: "";
}
.v-row:after { clear: both;}
.v-col{
	padding-left: .4rem;
    padding-right: .4rem;
}
.v-col .v-row { margin:0; }
[class*=v-col-] {
    float: left;
    box-sizing: border-box;
}
.v-col-1 { width: 4.16667%;}
.v-col-2 { width: 8.33333%;}
.v-col-3 { width: 12.5%;}
.v-col-4 { width: 16.66667%;}
.v-col-5 { width: 20.83333%;}
.v-col-6 { width: 25%;}
.v-col-7 { width: 29.16667%;}
.v-col-8 { width: 33.33333%;}
.v-col-9 { width: 37.5%;}
.v-col-10 { width: 41.66667%;}
.v-col-11 { width: 45.83333%;}
.v-col-12 { width: 50%;}
.v-col-13 { width: 54.16667%;}
.v-col-14 { width: 58.33333%;}
.v-col-15 { width: 62.5%;}
.v-col-16 { width: 66.66667%;}
.v-col-17 { width: 70.83333%;}
.v-col-18 { width: 75%;}
.v-col-19 { width: 79.16667%;}
.v-col-20 { width: 83.33333%;}
.v-col-21 { width: 87.5%;}
.v-col-22 { width: 91.66667%;}
.v-col-23 { width: 95.83333%;}
.v-col-24 { width: 100%;}
.v-grid-content{
	display: block;
    min-height: 36px;
    padding: .4rem;
    border: 1px solid #ddd;
    box-shadow: 0 0 2px #ddd;
    background: white;
    overflow: hidden;
}
/* v-row-flex 布局 */
.v-row-flex{ display: flex;}

/* v-title */
.v-title{
	padding:0 .4rem;
}
.v-title h1{
	line-height: 1.4rem;
}
.v-title span{
	font-size: .6rem;
	color:#999;
	text-align: right;
	display: block;
}

/* v-icon */
.v-icon{
	width: 2.2rem;
    height: 2.2rem;
    line-height: 2.2rem;
    border-radius: 50%;
    margin-right: .5rem;
    font-size: 1rem;
    background: #00a69b;
    text-align: center;
    color: #fff;    
}
/* v-text */
.v-text.v-m-r{ margin-right:1.3rem;}
.v-text h2{ font-size: 1.2rem;}
.v-text p{
	font-size: .6rem;
	color: #999;
}
.v-text p span{ margin-left: .5rem;}
.v-text-right{ text-align:right;}
.v-row-flex+.v-text{ margin-top:.4rem;}
/* 颜色 v-bg */
.v-bg{ background: #f180c4;}
.v-bg2{ background: #ffb64a;}
.v-bg3{ background: #7ec3fd;}
.v-bg4{ background: #968af5;}
.v-bg5{ background: #78d487;}
```
