### ISSUE TITLE
 Flex 布局：语法篇

### ISSUE THREAD

**Issue by GjXing** [GjXing/vueBlog#25]
### 网页布局（layout）是 CSS 的一个重点应用
布局的传统解决方案，基于[`盒状模型`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)，依赖[`display`](https://developer.mozilla.org/en-US/docs/Web/CSS/display)属性 +[ `position`](https://developer.mozilla.org/en-US/docs/Web/CSS/position)属性 + [`float`](https://developer.mozilla.org/en-US/docs/Web/CSS/float)属性。它对于那些特殊布局非常不方便，比如，`垂直居中`就不容易实现。

> 兼容性

![image](https://user-images.githubusercontent.com/14285531/30790116-9b06237e-a1dc-11e7-8513-ce91bdb9c56f.png)

## 一、什么是Flex 布局？
Flex 是 Flexible Box 的缩写，意为"弹性布局"，用来为盒状模型提供最大的灵活性。
任何一个容器都可以指定为 Flex 布局。

```css
.box{
  display: flex;
}
```

行内元素也可以使用 Flex 布局。

```css
.box{
  display: inline-flex;
}
```

Webkit 内核的浏览器，必须加上-webkit前缀。

```css
.box{
  display: -webkit-flex; /* Safari */
  display: flex;
}
```

注意，设为 Flex 布局以后，子元素的 `float `、 `clear` 和 `vertical-align` 属性将失效。

## 二、基本概念
采用 Flex 布局的元素，称为 Flex 容器（flex container），简称"容器"。它的所有子元素自动成为容器成员，称为 Flex 项目（flex item），简称"项目"。
![image](https://user-images.githubusercontent.com/14285531/30790360-0b31af1e-a1de-11e7-963e-119a9db2e7e9.png)

容器默认存在两根轴：水平的主轴（main axis）和垂直的交叉轴（cross axis）。
主轴的开始位置（与边框的交叉点）叫做 `main start` ，结束位置叫做 `main end` ；
交叉轴的开始位置叫做 `cross start` ，结束位置叫做 `cross end` 。
项目默认沿主轴排列。
单个项目占据的主轴空间叫做 `main size` ，占据的交叉轴空间叫做 `cross size` 。

## 三、容器的属性
以下6个属性设置在容器上。

```
  flex-direction
  flex-wrap
  flex-flow
  justify-content
  align-items
  align-content
```
> `flex-direction` 属性 决定主轴的方向（即项目的排列方向）。

```css
.box {
  flex-direction: row | row-reverse | column | column-reverse;
}
```

![image](https://user-images.githubusercontent.com/14285531/30790526-f57eb3aa-a1de-11e7-8d0f-f80f50b214c5.png)

值的表示

```
  row（默认值）：主轴为水平方向，起点在左端。
  row-reverse：主轴为水平方向，起点在右端。
  column：主轴为垂直方向，起点在上沿。
  column-reverse：主轴为垂直方向，起点在下沿。
```
> ` flex-wrap` 属性 默认情况下，项目都排在一条线（又称"轴线"）上。flex-wrap属性定义，如果一条轴线排不下，如何换行。

```css
.box{
  flex-wrap: nowrap | wrap | wrap-reverse;
}
```

（1） `nowrap` （默认）：不换行

![image](https://user-images.githubusercontent.com/14285531/30790768-8a912eae-a1e0-11e7-9519-274ad0a0af01.png)

（2） `wrap` ：换行，第一行在上方。

![image](https://user-images.githubusercontent.com/14285531/30790778-9e0cc90c-a1e0-11e7-9d68-f9b8fb208d6c.png)

（3） `wrap-reverse` ：换行，第一行在下方。

![image](https://user-images.githubusercontent.com/14285531/30790783-aba0ee40-a1e0-11e7-8753-f30b56da72b7.png)

> `flex-flow` 属性是 `flex-direction` 属性和 `flex-wrap` 属性的简写形式，默认值为 `row nowrap`

```css
.box {
  flex-flow: <flex-direction> || <flex-wrap>;
}
```

> ` justify-content` 属性定义了项目在主轴上的对齐方式

```css
.box {
  justify-content: flex-start | flex-end | center | space-between | space-around;
}
```

![image](https://user-images.githubusercontent.com/14285531/30790833-1b2c6b04-a1e1-11e7-9185-d3b6f434eef2.png)

具体对齐方式与轴的方向有关。下面假设主轴为从左到右。

```
  flex-start（默认值）：左对齐
  flex-end：右对齐
  center： 居中
  space-between：两端对齐，项目之间的间隔都相等。
  space-around：每个项目两侧的间隔相等。所以，项目之间的间隔比项目与边框的间隔大一倍。
```
> `align-items` 属性 定义项目在交叉轴上如何对齐

```css
.box {
  align-items: flex-start | flex-end | center | baseline | stretch;
}
```

![image](https://user-images.githubusercontent.com/14285531/30790886-6bdc90a6-a1e1-11e7-8ca3-488660b2695e.png)

具体的对齐方式与交叉轴的方向有关，下面假设交叉轴从上到下。

```
  flex-start：交叉轴的起点对齐。
  flex-end：交叉轴的终点对齐。
  center：交叉轴的中点对齐。
  baseline: 项目的第一行文字的基线对齐。
  stretch（默认值）：如果项目未设置高度或设为auto，将占满整个容器的高度。
```
> `align-content` 属性 定义了多根轴线的对齐方式。如果项目只有一根轴线，该属性不起作用。

```css
.box {
  align-content: flex-start | flex-end | center | space-between | space-around | stretch;
}
```

![image](https://user-images.githubusercontent.com/14285531/30790919-9d7dc94a-a1e1-11e7-9dd1-1c565cbabb15.png)

```
  flex-start：与交叉轴的起点对齐。
  flex-end：与交叉轴的终点对齐。
  center：与交叉轴的中点对齐。
  space-between：与交叉轴两端对齐，轴线之间的间隔平均分布。
  space-around：每根轴线两侧的间隔都相等。所以，轴线之间的间隔比轴线与边框的间隔大一倍。
  stretch（默认值）：轴线占满整个交叉轴。
```
## 四、项目的属性
```
  order //定义项目的排列顺序。数值越小，排列越靠前，默认为0

  flex-grow //定义项目的放大比例，默认为0，即如果存在剩余空间，也不放大。

  flex-shrink //定义了项目的缩小比例，默认为1，即如果空间不足，该项目将缩小

  flex-basis //定义了在分配多余空间之前，项目占据的主轴空间（main size）。浏览器根据这个属性，计算主轴是否有多余空间。它的默认值为auto，即项目的本来大小。

  flex //是flex-grow, flex-shrink 和 flex-basis的简写，默认值为0 1 auto。后两个属性可选 该属性有两个快捷值：auto (1 1 auto) 和 none (0 0 auto)。

  align-self //允许单个项目有与其他项目不一样的对齐方式，可覆盖align-items属性。默认值为auto，表示继承父元素
```
